#Stage-1 Build .NET Project (SDK-Image)
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /src

COPY Worker.csproj .

RUN dotnet restore

COPY . .

RUN dotnet publish -c Release -o /app/publish

#Stage 2: Runtime Image

FROM mcr.microsoft.com/dotnet/runtime:7.0 AS runtime

RUN groupadd -r appgroup && useradd -r -g appgroup appuser

WORKDIR /app

COPY --from=build /app/publish .

RUN chown -R appuser:appgroup /app

USER appuser

CMD ["dotnet", "Worker.dll"]